channels:
  - conda-forge
  - nodefaults
dependencies:
  # additional frameworks
  - xgboost
  - catboost
  - lightgbm
  - scikit-learn-intelex
  # sklbench dependencies
  - scikit-learn
  - pandas
  - pyarrow
  - h5py
  - openpyxl
  - tqdm
  - psutil
  - requests
  - py-cpuinfo
